version: '3.3'

services:
  mysql:
    image: mysql:5
    environment:
        - MYSQL_DATABASE=my_store
        - MYSQL_USER=
        - MYSQL_ROOT_PASSWORD=t32la
        - MYSQL_PORT=3306
    ports:
        - 3307:3306
    volumes:
        - ./mysql_data:/var/lib/mysql

